---
# Cilium configuration
cilium_namespace: "cilium"
cilium_repo_name: "cilium"
cilium_repo_url: "https://helm.cilium.io/"
cilium_release: "cilium"
cilium_chart_ref: "cilium/cilium"
cilium_chart_version: "1.15.0"

# Cilium values
cilium_values:
  kubeProxyReplacement: "false"
  k8sServiceHost: "172.16.250.23"
  k8sServicePort: "6443"
  operator:
    replicas: 1

# Timeouts
cilium_timeout: "10m"

