---
- name: Check if kubeconfig exists
  ansible.builtin.stat:
    path: "{{ kubeconfig_path }}"
  register: kubeconfig_stat
  failed_when: not kubeconfig_stat.stat.exists

- name: Add MetalLB Helm repository
  kubernetes.core.helm_repository:
    name: metallb
    repo_url: "https://metallb.github.io/metallb"
    state: present
  when: kubeconfig_stat.stat.exists

- name: Create MetalLB namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ metallb_namespace }}"
    state: present
  when: kubeconfig_stat.stat.exists

- name: Update Helm repositories
  ansible.builtin.shell: helm repo update
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  when: kubeconfig_stat.stat.exists

- name: Install/Upgrade MetalLB Helm chart
  kubernetes.core.helm:
    name: "{{ metallb_release_name }}"
    chart_ref: "{{ metallb_chart_name }}"
    release_namespace: "{{ metallb_namespace }}"
    values:
      speaker:
        nodeSelector:
          node-role.kubernetes.io/control-plane: ""
      controller:
        nodeSelector:
          node-role.kubernetes.io/control-plane: ""
    state: present
    update_repo_cache: true
  when: kubeconfig_stat.stat.exists
  timeout: 600

- name: Wait for ALL MetalLB pods to be ready
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    namespace: "{{ metallb_namespace }}"
  register: metallb_pods
  retries: 60
  delay: 10
  until: 
    - metallb_pods.resources | length > 0
    - metallb_pods.resources | selectattr('status.phase', 'equalto', 'Running') | list | length == metallb_pods.resources | length
    - metallb_pods.resources | selectattr('status.conditions', 'defined') | 
      selectattr('status.conditions', 'defined') | 
      map(attribute='status.conditions') | 
      flatten | 
      selectattr('type', 'equalto', 'Ready') | 
      selectattr('status', 'equalto', 'True') | list | length == metallb_pods.resources | length
  when: kubeconfig_stat.stat.exists

- name: Create IPAddressPool and L2Advertisement INLINE
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig_path }}"
    definition:
      - apiVersion: metallb.io/v1beta1
        kind: IPAddressPool
        metadata:
          name: default
          namespace: "{{ metallb_namespace }}"
        spec:
          addresses:
          - 172.16.111.3-172.16.111.15
      - apiVersion: metallb.io/v1beta1
        kind: L2Advertisement
        metadata:
          name: default
          namespace: "{{ metallb_namespace }}"
        spec:
          ipAddressPools:
          - default
  when: kubeconfig_stat.stat.exists

