---
galaxy_info:
  author: your.name
  description: Install NGINX Ingress Controller
  company: your.company
  license: MIT
  min_ansible_version: 2.10
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - kubernetes
    - nginx
    - ingress
    - helm
dependencies: []

