---
galaxy_info:
  author: your.name
  description: Install Kubernetes with containerd
  company: your.company
  license: MIT
  min_ansible_version: 2.10
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
dependencies: []

