---
galaxy_info:
  author: "envy"
  description: "Install Cilium CNI with Helm for Kubernetes"
  company: "homelab"
  license: MIT
  min_ansible_version: 2.10
  platforms:
    - name: Ubuntu
      versions:
        - bookworm
        - jammy
  galaxy_tags:
    - kubernetes
    - cilium
    - cni
    - networking
dependencies: []

