planka_secretkey: "8215c330360e427326a0c52d6d931fac68d4610a6f8895b0a85aaf402e3a86d74027f02731714fec4bbcbaf07faa1b7e1f622a4c01b60c08894b7ff1ff8e8337"
planka_admin_email: "admin@env.admin"
planka_admin_password: "pas$!23"
planka_admin_name: "admin"
planka_admin_username: "plankaeb"
planka_oidc_client_id: "UL77Nh2Dnlw5aumJsFJt3igRbM6ke8AYMFkYwkBz"
planka_oidc_client_secret: "ILh7CSw8cAjjGh3DD4O2gOYvFCahzNcszqnPP27CUFMMxfyF4MByRsrhpIWpoFAStau3m7730hlR4sLs2cJpIjq7E8bi4LCGPMIOXrC4tdJmvahBtOeSYnSHUxocwes5"

nextcloud_host: "nextcloud.k8s-01.idi.nahui"
collabora_host: "collabora.k8s-01.idi.nahui"

nextcloud_admin_username: "admin"
nextcloud_admin_password: "qwerty123"

mariadb_username: "nextcloud"
mariadb_password: "qwerty123"
mariadb_root_password: "qwerty123"

redis_password: "qwerty123"

collabora_username: "admin"
collabora_password: "qwerty123"

