---
# Longhorn configuration
longhorn_namespace: "longhorn-system"
longhorn_repo_name: "longhorn"
longhorn_repo_url: "https://charts.longhorn.io"
longhorn_release_name: "longhorn"
longhorn_chart_ref: "longhorn/longhorn"
longhorn_data_path: "/data/slowstorageclass"
longhorn_slow_storageclass: "longhorn-slow"

# StorageClass parameters
longhorn_replicas: "3"
longhorn_stale_timeout: "2880"
longhorn_default_class: false

