namespace: "metallb-system"

commonLabels: {}

IPAddressPools:
  annotations: {}
  additionalLabels: {}
  pools:
  - name: my-pool
    addresses:
    - 172.16.111.3 - 172.16.111.15

BFDProfiles:
  annotations: {}
  additionalLabels: {}
  profiles:
  - name: my-profile
    additionalLabels:
      receiveInterval: 380
      transmitInterval: 270

BGPAdvertisements:
  annotations: {}
  additionalLabels: {}
  advertisements:
  - name: my-adv
    additionalLabels: {}
    ipAddressPools:  
    - my-pool

BGPPeers:
  annotations: {}
  additionalLabels: {}
  peers:
  - name: my-peer
    myASN: 228
    peerASN: 1337
    peerAddress: 172.16.250.1
    bfdProfile: my-profile

