---
- name: Tap fluxcd repository
  community.general.homebrew_tap:
    name: fluxcd/tap
    state: present
  become: no
  tags:
    - install
    - darwin

- name: Install flux CLI
  community.general.homebrew:
    name: fluxcd/tap/flux
    state: latest
  become: no
  tags:
    - install
    - darwin
