namespace: "metallb-system"

IPAddressPools:
  pools:
  - name: my-pool
    addresses:
    - 172.16.111.3 - 172.16.111.15

BGPAdvertisements:
  advertisements:
  - name: my-adv
    ipAddressPools:  
    - my-pool

BGPPeers:
  peers:
  - name: my-peer
    myASN: 228
    peerASN: 1337
    peerAddress: 172.16.250.1
    bfdProfile: my-profile

