---
# Cert-manager configuration
certmanager_namespace: "cert-manager"
certmanager_repo_name: "jetstack"
certmanager_repo_url: "https://charts.jetstack.io"
certmanager_release_name: "cert-manager"
certmanager_chart_ref: "jetstack/cert-manager"
certmanager_deployment_name: "cert-manager"

# Installation options
certmanager_install_crds: true
certmanager_wait: false

# Replicas and resources
certmanager_replicas: 1
certmanager_cpu_request: "100m"
certmanager_memory_request: "256Mi"

# Wait timeout
certmanager_wait_timeout: "5m"

